config/routes.rb
CharadesVn::Application.routes.draw do
  get "home/index"
  get "home/new"
  get "sessions/new"
  get "users/new"
  get "welcome/index"

  root 'home#index'

  resources :categories do
    resources :words
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :users
  resources :sessions
  resources :clients, :only => [:show, :index]

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true,
                    length: { minimum: 5 }
	validates :description, presence: true,
                    length: { minimum: 5 }
     
    validates :hash_code, presence: true,
    				length: { is: 32 }              
	has_many :words, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	 #attr_accessible :email, :password, :password_confirmation
  
  	attr_accessor :password
  	before_save :encrypt_password
  
  	validates_confirmation_of :password
  	validates_presence_of :password, :on => :create
  	validates_presence_of :email
  	validates_uniqueness_of :email
  
  	def self.authenticate(email, password)
    	user = find_by_email(email)
    	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    		user
    	else
    		nil
    	end
  	end
  
  	def encrypt_password
    	if password.present?
    		self.password_salt = BCrypt::Engine.generate_salt
    		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    	end
  	end
end

app/models/word.rb
class Word < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

  	helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def require_login
    	@current_user = current_user
    	if @current_user.nil?
    		flash[:error] = "You must be logged in to access this section"
        	redirect_to root_path
      	end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
 		@category.published = false
 		
 		wordsList = params[:category][:words].split(';')
 		wordsList.each do |word|
 			w = Word.new(:word => word, :published => false, :category_id => @category.id )
			@category.words.push(w)
		end

 		require 'digest/md5'
		digest = Digest::MD5.hexdigest(@category.name+@category.description)
		@category.hash_code = digest

 		if @category.save
			redirect_to category_path(@category)
		else
			render 'new'
		end

	end

	def show
	  	@category = Category.find(params[:id]) #where(hash_code: params[:id]).first
	  	@count = @category.words.length
	  	respond_to do |format|
	  		format.html
	  		#format.xml
	  	end
	end

	def index
		@categories = Category.all

		respond_to do |format|
	  		format.html
	  		#format.xml
	  	end
	end

	def edit
	  	@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])

		wordsList = params[:category][:words].split(';')
 		wordsList.each do |word|
 			w = Word.new(:word => word, :published => false, :category_id => @category.id )
			@category.words.push(w)
		end

		require 'digest/md5'
		digest = Digest::MD5.hexdigest(category_params[:name]+category_params[:description])
		@category.hash_code = digest

		if @category.update(category_params)
			redirect_to @category
		else
			render 'edit'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
	 
		redirect_to welcome_index_path
	end

	private
	  def category_params
	    params.require(:category).permit(:name, :description, :published, :instruction)
	  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	skip_before_action :require_login
	
	def show
	  	@category = Category.where(hash_code: params[:id]).first

	  	connection = ActiveRecord::Base.connection()
	  	@words = connection.execute("select word from words where category_id =" + @category.id.to_s + " ORDER BY RAND() LIMIT 150")
	  	@count = @words.size
	  	respond_to do |format|
	  		format.html
	  		format.xml
	  	end
	end

	def index
		@categories = Category.all

		respond_to do |format|
	  		format.html
	  		format.xml
	  	end
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :require_login
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_login
	def new
	end

	def create
		user = User.authenticate(params[:email], params[:password])
		if user
			session[:user_id] = user.id
			redirect_to welcome_index_path
		else
			flash.now.alert = "Invalid email or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :require_login
	def new
  		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url, :notice => "Signed up!"
		else
			render "new"
		end
	end

	private
		def user_params
			params.require(:user).permit(:email, :password, :password_confirmation)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
  def index
  	@categories = Category.all
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

	def new
		@word = Word.new
	end

	def create
		@word = Word.new(word_params)
		@word.category_id = params[:category_id]
 		if @word.save
			redirect_to category_path(@word.category_id)
		else
			render 'new'
		end
	end

	def edit
	  	@word = Word.find(params[:id])
	end

	def update
		@word = Word.find(params[:id])

		if @word.update(word_params)
			redirect_to category_path(@word.category_id)
		else
			render 'edit'
		end
	end

	def destroy
		@word = Word.find(params[:id])
		@word.destroy
	 
		redirect_to category_path(@word.category_id)
	end

	private
	  def word_params
	    params.require(:word).permit(:word, :published, :category_id)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/categories/edit.html.erb
<h1>Editing category</h1>
 
<%= form_for :category, url: category_path(@category), method: :patch do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:</h2>
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, :cols => "100", :rows => "10" %>
  </p>

  <p>
    <%= f.label :instruction %><br>
    <%= f.text_area :instruction, :cols => "100", :rows => "10" %>
  </p>
 
  <p>
    <%= f.label :publish %><br>
    <%= f.check_box :published %>
  </p> 

  <p>
    <%= f.label :NewWords %><br>
    <%= f.text_area :words, :cols => "100", :rows => "10"%>
  </p> 
  <p>
    (De insert nhieu chu vao database cung 1 luc: xoa het content trong khung words di, copy het tat ca cac chu muon insert vao khung nay, separated by semi-colon ';'
    Vi du: word1;word2;word3; => insert word1, word2, word3 to database)
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/index.html.erb
<h1>All categories</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>HowToPlay</th>
    <th>Published</th>
  </tr>
 
  <% @categories.each do |cat| %>
    <tr>
      <td><%= link_to "#{cat.name}", category_path(cat) %></td>
      <td><%= truncate( "#{cat.description}", :length => 30) %></td>
      <td><%= truncate( "#{cat.instruction}", :length => 30) %></td>
      <td><%= cat.published %></td>
    </tr>
  <% end %>
</table>

app/views/categories/index.xml.erb
<?xml version="1.0" encoding="utf-8"?>
<categories>
	<% @categories.each do |cat| %>
		<category id="<%= cat.id %>" mode="<%= cat.description %>" name="<%= cat.name %>"/>
	<% end %>
</categories>

app/views/categories/new.html.erb
<%= form_for :category, url: categories_path do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:</h2>
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description , :cols => "100", :rows => "10"%>
  </p>

  <p>
    <%= f.label :instruction %><br>
    <%= f.text_area :instruction, :cols => "100", :rows => "10"%>
  </p>
 
  <p>
    <%= f.label :words %><br>
    <%= f.text_area :words, :cols => "100", :rows => "10"%>
  </p> 

  <p>
    (De insert nhieu chu vao database cung 1 luc: xoa het content trong khung words di, copy het tat ca cac chu muon insert vao khung nay, separated by semi-colon ';'
    Vi du: word1;word2;word3; => insert word1, word2, word3 to database)
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/show.html.erb
<% if @category %>
	<h2><%= link_to 'Edit this category', edit_category_path(@category) %></h2>

	<p>
	  <strong>Name:</strong>
	  <%= @category.name %>
	</p>
	 
	<p>
	  <strong>Description:</strong>
	  <%= @category.description %>
	</p>

	<p>
	  <strong>How to play:</strong>
	  <%= @category.instruction %>
	</p>

	<p>
	  <strong>Published:</strong>
	  <%= @category.published %>
	</p>

	<p>
	  <strong>Client code:</strong>
	  <%= link_to "#{@category.hash_code}", client_path(@category.hash_code) %>
	</p>

	<h2>Words list: <%= @count %> words <p class="right"><%= link_to "Add New Word", new_category_word_path(@category.id) %></p></h2>
	
	<table>
		<tr>
			<th>Word</th>
	    	<th>Status</th>
		</tr>
		<% @category.words.each do |word| %>
		<tr>
	    	<td><%= word.word %></td>
	    	<% if word.published %>
        		<td>published</td>
        	<% else %>
        		<td>not published</td>
        	<% end %>
	    	<td><%= link_to 'Edit', [:edit, word.category, word] %></td>
      		<td><%= link_to 'Delete', [word.category, word],
                	    method: :delete, data: { confirm: 'Are you sure?' } %></td>
        	
		</tr>
		<% end %>
	</table>
	
<% end %>

app/views/categories/show.xml.erb
<category>
	<% @category.words.each do |word| %>
	  <word name="<%= word %>"/>
	<% end %>
</category>

app/views/clients/index.html.erb
<h1> CLIENT VIEW </h1>

<h1>All categories</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>HowToPlay</th>
    <th>Published</th>
  </tr>
 
  <% @categories.each do |cat| %>
    <tr>
      <td><%= link_to "#{cat.name}", client_path(cat.hash_code) %></td>
      <td><%= truncate( "#{cat.description}", :length => 30) %></td>
      <td><%= truncate( "#{cat.instruction}", :length => 30) %></td>
      <td><%= cat.published %></td>
    </tr>
  <% end %>
</table>

app/views/clients/index.xml.erb
<?xml version="1.0" encoding="utf-8"?>
<categories>
	<% @categories.each do |cat| %>
		<category id="<%= cat.hash_code %>" mode="<%= cat.description %>" name="<%= cat.name %>" instruction="<%= cat.instruction %>"/>
	<% end %>
</categories>

app/views/clients/show.html.erb
<h1> CLIENT VIEW </h1>

<% if @category %>
	<p>
	  <strong>Category Name:</strong>
	  <%= @category.name %>
	</p>
	 
	<p>
	  <strong>Category Description:</strong>
	  <%= @category.description %>
	</p>

	<p>
	  <strong>Category Instruction:</strong>
	  <%= @category.instruction %>
	</p>

	<%= link_to 'Back to Admin view', category_path(@category) %>
	<h2>Words list:  <%= @count %> words </h2>
	<% @category.words.each do |word| %>
	  <p>
	    <%= word.word %>
	  </p>
	<% end %>
<% end %>

app/views/clients/show.xml.erb
<category>
	<% @words.each do |word| %>
	  <word name="<%= word[0] %>"/>
	<% end %>
</category>

app/views/home/index.html.erb
<h1>Log in</h1>

<%= form_tag sessions_path do %>
  <p>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, params[:email] %>
  </p>
  <p>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </p>
  <p class="button"><%= submit_tag "Log in" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel="tictocLogo" href="/images/tictocLogo.png"/>
	  <title>iDoan</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<% if current_user %>
			<header class="header">
				<nav>
					<%= link_to "Home", controller: "welcome" %>
					<%= link_to "New category", new_category_path %>

					<div class="login">
						<% if current_user %>
							<strong><%= current_user.email %></strong>
							<%= link_to "Log out", log_out_path %>
						<% else %>
							<%= link_to "Sign up", sign_up_path %> or
							<%= link_to "log in", log_in_path %>
						<% end %>
					</div>
				</nav>
			</header>
		<% end %>

		<br>
		<br>
		<section class="main_middle">
			<%= yield %>
		</section>


		<br><br>
		<footer class="footer">
				<img src="/images/tictocLogo.png" alt="logo" />
				<h1>Vegas, where everything begins</h1>
				<div class="copyright">
					<small>Copyright 2014 Tic Toc Production. All rights reserved</small>
				</div>
		</footer>

	</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/welcome/index.html.erb
<h1>All categories</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>HowToPlay</th>
    <th>Published</th>
  </tr>
 
  <% @categories.each do |cat| %>
    <tr>
      <td><%= link_to "#{cat.name}", category_path(cat) %></td>
      <td><%= truncate( "#{cat.description}", :length => 30) %></td>
      <td><%= truncate( "#{cat.instruction}", :length => 30) %></td>
      <td><%= cat.published %></td>
      <td><%= link_to 'Edit', edit_category_path(cat) %></td>
      <td><%= link_to 'Delete', category_path(cat),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/words/edit.html.erb
<h1>Editing word</h1>
 
<%= form_for :word, url: category_word_path(@word.category, @word), method: :patch do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited
        this word from being saved:</h2>
      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </p>

  <p>
    <%= f.label :publish %><br>
    <%= f.check_box :published %>
  </p> 
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/words/new.html.erb
<h1>Add new word</h1>

<%= form_for :word, url: category_words_path, method: :post do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited
        this word from being saved:</h2>
      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </p>

  <p>
    <%= f.label :publish %><br>
    <%= f.check_box :published %>
  </p> 
 
  <p>
    <%= f.submit %>
  </p>
<% end %>